### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms 

### ISSUE THREAD

**Issue by Hard-Coder05** [camunda-community-hub/bpmn-spec#104]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

__Describe the solution you'd like__

This repository currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use this repo's issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
I would like to work on this issue!

**Comment by saig0** [comment]
@Hard-Coder05 thank you for raising this up.

I'm not sure about it yet. I need to check if it can offer value for this project. 

---

Please note that I would **not** consider this for the **Hacktoberfest** since it doesn't add much value to the project (i.e. the codebase). Look at [these issues](https://github.com/camunda-community-hub/bpmn-spec/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) if you want to contribute for the Hacktoberfest.

**Comment by Hard-Coder05** [comment]
@saig0 Okay  i will look into some other issues then!
